In [1]:
from pathlib import Path
import sys

import polars as pl
from IPython.display import display


def _find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").exists():
            return candidate
    raise FileNotFoundError("Unable to locate the repository root from the notebook working directory.")


REPO_ROOT = _find_repo_root(Path.cwd())
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

CACHE_ROOT = REPO_ROOT / "cache"

from wind_datasets.models import TaskSpec
from wind_datasets.persistence import PersistenceExperimentResult, run_persistence_experiment

PERSISTENCE_TASK = TaskSpec.next_6h_from_24h()


def _round_metrics(frame: pl.DataFrame) -> pl.DataFrame:
    rounded_columns = [column for column in ["mae_kw", "rmse_kw", "mae_pu", "rmse_pu"] if column in frame.columns]
    if not rounded_columns:
        return frame
    return frame.with_columns([pl.col(column).round(3) for column in rounded_columns])


def display_persistence_result(result: PersistenceExperimentResult) -> PersistenceExperimentResult:
    summary = _round_metrics(result.summary).with_columns(
        [
            pl.col("start_timestamp").dt.strftime("%Y-%m-%d %H:%M:%S"),
            pl.col("end_timestamp").dt.strftime("%Y-%m-%d %H:%M:%S"),
        ]
    )
    per_horizon = _round_metrics(result.per_horizon.sort("horizon_step"))
    per_turbine = _round_metrics(result.per_turbine)
    display(summary)
    display(per_horizon)
    display(per_turbine)
    return result

In [2]:
# kelmarsh
kelmarsh_result = run_persistence_experiment(
    "kelmarsh",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(kelmarsh_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ kelmarsh   ┆ default    ┆ 2050.0     ┆ 6        ┆ … ┆ 0.121  ┆ 0.188   ┆ 2016-01-03 ┆ 2024-12-31 │
│            ┆            ┆            ┆          ┆   ┆        ┆         ┆ 00:00:00   ┆ 23:50:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 2641667       ┆ 93.0    ┆ 153.675 ┆ 0.045  ┆ 0.075   │
│ 2            ┆ 20              ┆ 2641667       ┆ 124.905 ┆ 203.042 ┆ 0.061  ┆ 0.099   │
│ 3            ┆ 30              ┆ 2641667       ┆ 143.617 ┆ 230.915 ┆ 0.07   ┆ 0.113   │
│ 4            ┆ 40              ┆ 2641667       ┆ 157.468 ┆ 251.115 ┆ 0.077  ┆ 0.122   │
│ 5            ┆ 50              ┆ 2641667       ┆ 168.787 ┆ 267.445 ┆ 0.082  ┆ 0.13    │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 2641667       ┆ 316.293 ┆ 468.623 ┆ 0.154  ┆ 0.229   │
│ 33           ┆ 330             ┆ 2641667       ┆ 320.027 ┆ 473.421 ┆ 0.156  ┆ 0.231   │
│ 34           ┆ 340             ┆ 2641667       ┆ 323.618 ┆ 478.043 ┆ 0.158  ┆ 0.233   │
│ 35           ┆ 350             ┆ 2641667       ┆ 327.185 ┆ 482.577 ┆ 0.16   ┆ 0.235   │
│ 36           ┆ 360             ┆ 2641667       ┆ 330.606 ┆ 486.98  ┆ 0.161  ┆ 0.238   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (6, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ Kelmarsh 1 ┆ 2050.0        ┆ 442592        ┆ 15933312     ┆ 250.655 ┆ 387.038 ┆ 0.122  ┆ 0.189   │
│ Kelmarsh 2 ┆ 2050.0        ┆ 444783        ┆ 16012188     ┆ 258.902 ┆ 394.363 ┆ 0.126  ┆ 0.192   │
│ Kelmarsh 3 ┆ 2050.0        ┆ 441356        ┆ 15888816     ┆ 256.359 ┆ 396.447 ┆ 0.125  ┆ 0.193   │
│ Kelmarsh 4 ┆ 2050.0        ┆ 438563        ┆ 15788268     ┆ 244.331 ┆ 379.266 ┆ 0.119  ┆ 0.185   │
│ Kelmarsh 5 ┆ 2050.0        ┆ 437738        ┆ 15758568     ┆ 249.71  ┆ 390.871 ┆ 0.122  ┆ 0.191   │
│ Kelmarsh 6 ┆ 2050.0        ┆ 436635        ┆ 15718860     ┆ 224.059 ┆ 358.857 ┆ 0.109  ┆ 0.175   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu  ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---     ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64     ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64        ┆          ┆   ┆         ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ kelmarsh   ┆ default    ┆ 2050.0     ┆ 6        ┆ … ┆ 0.12068 ┆ 0.187678 ┆ 2016-01-0 ┆ 2024-12-3 │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ 3         ┆ 1         │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ 00:00:00  ┆ 23:50:00  │
└────────────┴────────────┴────────────┴──────────┴───┴─────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 2641667       ┆ 92.999595  ┆ 153.6753   ┆ 0.045366 ┆ 0.074964 │
│ 2            ┆ 20              ┆ 2641667       ┆ 124.904623 ┆ 203.042098 ┆ 0.060929 ┆ 0.099045 │
│ 3            ┆ 30              ┆ 2641667       ┆ 143.616838 ┆ 230.91462  ┆ 0.070057 ┆ 0.112641 │
│ 4            ┆ 40              ┆ 2641667       ┆ 157.467857 ┆ 251.115016 ┆ 0.076814 ┆ 0.122495 │
│ 5            ┆ 50              ┆ 2641667       ┆ 168.787367 ┆ 267.444623 ┆ 0.082335 ┆ 0.130461 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 2641667       ┆ 316.292848 ┆ 468.623117 ┆ 0.154289 ┆ 0.228597 │
│ 33           ┆ 330             ┆ 2641667       ┆ 320.026566 ┆ 473.421257 ┆ 0.156111 ┆ 0.230937 │
│ 34           ┆ 340             ┆ 2641667       ┆ 323.617862 ┆ 478.042615 ┆ 0.157862 ┆ 0.233192 │
│ 35           ┆ 350             ┆ 2641667       ┆ 327.185475 ┆ 482.576782 ┆ 0.159603 ┆ 0.235403 │
│ 36           ┆ 360             ┆ 2641667       ┆ 330.606042 ┆ 486.979789 ┆ 0.161271 ┆ 0.237551 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (6, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ Kelmarsh 1 ┆ 2050.0     ┆ 442592     ┆ 15933312   ┆ 250.655033 ┆ 387.03829 ┆ 0.122271 ┆ 0.188799 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Kelmarsh 2 ┆ 2050.0     ┆ 444783     ┆ 16012188   ┆ 258.902195 ┆ 394.36294 ┆ 0.126294 ┆ 0.192372 │
│ Kelmarsh 3 ┆ 2050.0     ┆ 441356     ┆ 15888816   ┆ 256.35862  ┆ 396.44714 ┆ 0.125053 ┆ 0.193389 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ Kelmarsh 4 ┆ 2050.0     ┆ 438563     ┆ 15788268   ┆ 244.330555 ┆ 379.26575 ┆ 0.119186 ┆ 0.185008 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Kelmarsh 5 ┆ 2050.0     ┆ 437738     ┆ 15758568   ┆ 249.710233 ┆ 390.87115 ┆ 0.12181  ┆ 0.190669 │
│ Kelmarsh 6 ┆ 2050.0     ┆ 436635     ┆ 15718860   ┆ 224.059456 ┆ 358.85733 ┆ 0.109297 ┆ 0.175052 │
│            ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [3]:
# penmanshiel
penmanshiel_result = run_persistence_experiment(
    "penmanshiel",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(penmanshiel_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ penmanshie ┆ default    ┆ 2050.0     ┆ 14       ┆ … ┆ 0.137  ┆ 0.221   ┆ 2016-06-02 ┆ 2024-12-31 │
│ l          ┆            ┆            ┆          ┆   ┆        ┆         ┆ 17:40:00   ┆ 23:50:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 5405463       ┆ 93.841  ┆ 163.922 ┆ 0.046  ┆ 0.08    │
│ 2            ┆ 20              ┆ 5405463       ┆ 129.778 ┆ 224.378 ┆ 0.063  ┆ 0.109   │
│ 3            ┆ 30              ┆ 5405463       ┆ 151.008 ┆ 257.312 ┆ 0.074  ┆ 0.126   │
│ 4            ┆ 40              ┆ 5405463       ┆ 166.915 ┆ 281.487 ┆ 0.081  ┆ 0.137   │
│ 5            ┆ 50              ┆ 5405463       ┆ 180.345 ┆ 301.687 ┆ 0.088  ┆ 0.147   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 5405463       ┆ 368.081 ┆ 558.016 ┆ 0.18   ┆ 0.272   │
│ 33           ┆ 330             ┆ 5405463       ┆ 372.857 ┆ 564.051 ┆ 0.182  ┆ 0.275   │
│ 34           ┆ 340             ┆ 5405463       ┆ 377.536 ┆ 570.0   ┆ 0.184  ┆ 0.278   │
│ 35           ┆ 350             ┆ 5405463       ┆ 382.205 ┆ 575.893 ┆ 0.186  ┆ 0.281   │
│ 36           ┆ 360             ┆ 5405463       ┆ 386.819 ┆ 581.639 ┆ 0.189  ┆ 0.284   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (14, 8)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id   ┆ rated_power_ ┆ eligible_win ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ kw           ┆ dows         ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str          ┆ ---          ┆ ---          ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│              ┆ f64          ┆ i64          ┆ i64          ┆         ┆         ┆        ┆         │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ Penmanshiel  ┆ 2050.0       ┆ 373157       ┆ 13433652     ┆ 284.58  ┆ 455.726 ┆ 0.139  ┆ 0.222   │
│ 01           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 372824       ┆ 13421664     ┆ 282.995 ┆ 455.297 ┆ 0.138  ┆ 0.222   │
│ 02           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 370240       ┆ 13328640     ┆ 280.819 ┆ 452.658 ┆ 0.137  ┆ 0.221   │
│ 04           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 372353       ┆ 13404708     ┆ 278.401 ┆ 450.076 ┆ 0.136  ┆ 0.22    │
│ 05           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 371045       ┆ 13357620     ┆ 275.941 ┆ 451.497 ┆ 0.135  ┆ 0.22    │
│ 06           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ …            ┆ …            ┆ …            ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ Penmanshiel  ┆ 2050.0       ┆ 412236       ┆ 14840496     ┆ 277.775 ┆ 445.994 ┆ 0.135  ┆ 0.218   │
│ 11           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 417785       ┆ 15040260     ┆ 294.18  ┆ 469.169 ┆ 0.144  ┆ 0.229   │
│ 12           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 418476       ┆ 15065136     ┆ 297.512 ┆ 474.182 ┆ 0.145  ┆ 0.231   │
│ 13           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 416576       ┆ 14996736     ┆ 292.336 ┆ 468.391 ┆ 0.143  ┆ 0.228   │
│ 14           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 416763       ┆ 15003468     ┆ 287.698 ┆ 460.778 ┆ 0.14   ┆ 0.225   │
│ 15           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_pow ┆ turbines ┆ … ┆ mae_pu   ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ er_kw     ┆ ---      ┆   ┆ ---      ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---       ┆ i64      ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64       ┆          ┆   ┆          ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ penmanshie ┆ default    ┆ 2050.0    ┆ 14       ┆ … ┆ 0.136658 ┆ 0.220651 ┆ 2016-06-0 ┆ 2024-12-3 │
│ l          ┆            ┆           ┆          ┆   ┆          ┆          ┆ 2         ┆ 1         │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ 17:40:00  ┆ 23:50:00  │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 5405463       ┆ 93.841083  ┆ 163.922004 ┆ 0.045776 ┆ 0.079962 │
│ 2            ┆ 20              ┆ 5405463       ┆ 129.778479 ┆ 224.378122 ┆ 0.063307 ┆ 0.109453 │
│ 3            ┆ 30              ┆ 5405463       ┆ 151.008225 ┆ 257.311688 ┆ 0.073663 ┆ 0.125518 │
│ 4            ┆ 40              ┆ 5405463       ┆ 166.915208 ┆ 281.486787 ┆ 0.081422 ┆ 0.137311 │
│ 5            ┆ 50              ┆ 5405463       ┆ 180.344707 ┆ 301.68679  ┆ 0.087973 ┆ 0.147164 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 5405463       ┆ 368.081414 ┆ 558.016302 ┆ 0.179552 ┆ 0.272203 │
│ 33           ┆ 330             ┆ 5405463       ┆ 372.857095 ┆ 564.050917 ┆ 0.181882 ┆ 0.275147 │
│ 34           ┆ 340             ┆ 5405463       ┆ 377.536423 ┆ 569.999683 ┆ 0.184164 ┆ 0.278049 │
│ 35           ┆ 350             ┆ 5405463       ┆ 382.20489  ┆ 575.893042 ┆ 0.186441 ┆ 0.280923 │
│ 36           ┆ 360             ┆ 5405463       ┆ 386.818896 ┆ 581.63851  ┆ 0.188692 ┆ 0.283726 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (14, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ Penmanshie ┆ 2050.0     ┆ 373157     ┆ 13433652   ┆ 284.579514 ┆ 455.72555 ┆ 0.138819 ┆ 0.222305 │
│ l 01       ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 372824     ┆ 13421664   ┆ 282.994838 ┆ 455.29748 ┆ 0.138046 ┆ 0.222096 │
│ l 02       ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 370240     ┆ 13328640   ┆ 280.818743 ┆ 452.65772 ┆ 0.136985 ┆ 0.220809 │
│ l 04       ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 372353     ┆ 13404708   ┆ 278.400531 ┆ 450.07611 ┆ 0.135805 ┆ 0.219549 │
│ l 05       ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 371045     ┆ 13357620   ┆ 275.940738 ┆ 451.49654 ┆ 0.134605 ┆ 0.220242 │
│ l 06       ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ Penmanshie ┆ 2050.0     ┆ 412236     ┆ 14840496   ┆ 277.774536 ┆ 445.99394 ┆ 0.1355   ┆ 0.217558 │
│ l 11       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 417785     ┆ 15040260   ┆ 294.180476 ┆ 469.1694  ┆ 0.143503 ┆ 0.228863 │
│ l 12       ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 418476     ┆ 15065136   ┆ 297.512236 ┆ 474.18245 ┆ 0.145128 ┆ 0.231309 │
│ l 13       ┆            ┆            ┆            ┆            ┆ 5         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 416576     ┆ 14996736   ┆ 292.335604 ┆ 468.39080 ┆ 0.142603 ┆ 0.228483 │
│ l 14       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 416763     ┆ 15003468   ┆ 287.698274 ┆ 460.77819 ┆ 0.140341 ┆ 0.22477  │
│ l 15       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [4]:
# hill_of_towie
hill_of_towie_result = run_persistence_experiment(
    "hill_of_towie",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(hill_of_towie_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ hill_of_to ┆ default    ┆ 2300.0     ┆ 21       ┆ … ┆ 0.13   ┆ 0.213   ┆ 2016-01-01 ┆ 2024-09-01 │
│ wie        ┆            ┆            ┆          ┆   ┆        ┆         ┆ 00:00:00   ┆ 00:00:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 9129924       ┆ 109.159 ┆ 192.06  ┆ 0.047  ┆ 0.084   │
│ 2            ┆ 20              ┆ 9129924       ┆ 151.699 ┆ 264.377 ┆ 0.066  ┆ 0.115   │
│ 3            ┆ 30              ┆ 9129924       ┆ 176.02  ┆ 304.184 ┆ 0.077  ┆ 0.132   │
│ 4            ┆ 40              ┆ 9129924       ┆ 193.293 ┆ 331.626 ┆ 0.084  ┆ 0.144   │
│ 5            ┆ 50              ┆ 9129924       ┆ 207.052 ┆ 352.825 ┆ 0.09   ┆ 0.153   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 9129924       ┆ 378.421 ┆ 589.71  ┆ 0.165  ┆ 0.256   │
│ 33           ┆ 330             ┆ 9129924       ┆ 382.746 ┆ 595.275 ┆ 0.166  ┆ 0.259   │
│ 34           ┆ 340             ┆ 9129924       ┆ 386.98  ┆ 600.748 ┆ 0.168  ┆ 0.261   │
│ 35           ┆ 350             ┆ 9129924       ┆ 391.15  ┆ 606.001 ┆ 0.17   ┆ 0.263   │
│ 36           ┆ 360             ┆ 9129924       ┆ 395.203 ┆ 611.104 ┆ 0.172  ┆ 0.266   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (21, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ T01        ┆ 2300.0        ┆ 436189        ┆ 15702804     ┆ 306.335 ┆ 498.164 ┆ 0.133  ┆ 0.217   │
│ T02        ┆ 2300.0        ┆ 435621        ┆ 15682356     ┆ 293.331 ┆ 484.567 ┆ 0.128  ┆ 0.211   │
│ T03        ┆ 2300.0        ┆ 436166        ┆ 15701976     ┆ 311.78  ┆ 503.996 ┆ 0.136  ┆ 0.219   │
│ T04        ┆ 2300.0        ┆ 435551        ┆ 15679836     ┆ 316.043 ┆ 510.578 ┆ 0.137  ┆ 0.222   │
│ T05        ┆ 2300.0        ┆ 435752        ┆ 15687072     ┆ 302.892 ┆ 493.763 ┆ 0.132  ┆ 0.215   │
│ …          ┆ …             ┆ …             ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ T17        ┆ 2300.0        ┆ 433358        ┆ 15600888     ┆ 269.305 ┆ 454.39  ┆ 0.117  ┆ 0.198   │
│ T18        ┆ 2300.0        ┆ 434521        ┆ 15642756     ┆ 268.205 ┆ 454.696 ┆ 0.117  ┆ 0.198   │
│ T19        ┆ 2300.0        ┆ 435327        ┆ 15671772     ┆ 313.135 ┆ 506.197 ┆ 0.136  ┆ 0.22    │
│ T20        ┆ 2300.0        ┆ 428020        ┆ 15408720     ┆ 306.612 ┆ 499.674 ┆ 0.133  ┆ 0.217   │
│ T21        ┆ 2300.0        ┆ 435751        ┆ 15687036     ┆ 308.63  ┆ 508.785 ┆ 0.134  ┆ 0.221   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬──────────┬────────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu  ┆ start_time ┆ end_times │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---      ┆ stamp      ┆ tamp      │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64      ┆ ---        ┆ ---       │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆          ┆ datetime[μ ┆ datetime[ │
│            ┆            ┆            ┆          ┆   ┆        ┆          ┆ s]         ┆ μs]       │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪══════════╪════════════╪═══════════╡
│ hill_of_to ┆ default    ┆ 2300.0     ┆ 21       ┆ … ┆ 0.1296 ┆ 0.213326 ┆ 2016-01-01 ┆ 2024-09-0 │
│ wie        ┆            ┆            ┆          ┆   ┆        ┆          ┆ 00:00:00   ┆ 1         │
│            ┆            ┆            ┆          ┆   ┆        ┆          ┆            ┆ 00:00:00  │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴──────────┴────────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 9129924       ┆ 109.159135 ┆ 192.060085 ┆ 0.04746  ┆ 0.083504 │
│ 2            ┆ 20              ┆ 9129924       ┆ 151.69886  ┆ 264.377176 ┆ 0.065956 ┆ 0.114947 │
│ 3            ┆ 30              ┆ 9129924       ┆ 176.020457 ┆ 304.183569 ┆ 0.076531 ┆ 0.132254 │
│ 4            ┆ 40              ┆ 9129924       ┆ 193.292714 ┆ 331.625678 ┆ 0.08404  ┆ 0.144185 │
│ 5            ┆ 50              ┆ 9129924       ┆ 207.05223  ┆ 352.824753 ┆ 0.090023 ┆ 0.153402 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 9129924       ┆ 378.420552 ┆ 589.710435 ┆ 0.164531 ┆ 0.256396 │
│ 33           ┆ 330             ┆ 9129924       ┆ 382.745584 ┆ 595.2748   ┆ 0.166411 ┆ 0.258815 │
│ 34           ┆ 340             ┆ 9129924       ┆ 386.980431 ┆ 600.747986 ┆ 0.168252 ┆ 0.261195 │
│ 35           ┆ 350             ┆ 9129924       ┆ 391.150343 ┆ 606.001403 ┆ 0.170065 ┆ 0.263479 │
│ 36           ┆ 360             ┆ 9129924       ┆ 395.202907 ┆ 611.1039   ┆ 0.171827 ┆ 0.265697 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (21, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ T01        ┆ 2300.0     ┆ 436189     ┆ 15702804   ┆ 306.335286 ┆ 498.16444 ┆ 0.133189 ┆ 0.216593 │
│            ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ T02        ┆ 2300.0     ┆ 435621     ┆ 15682356   ┆ 293.330627 ┆ 484.56703 ┆ 0.127535 ┆ 0.210681 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ T03        ┆ 2300.0     ┆ 436166     ┆ 15701976   ┆ 311.779993 ┆ 503.99594 ┆ 0.135557 ┆ 0.219129 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ T04        ┆ 2300.0     ┆ 435551     ┆ 15679836   ┆ 316.04349  ┆ 510.57760 ┆ 0.13741  ┆ 0.22199  │
│            ┆            ┆            ┆            ┆            ┆ 9         ┆          ┆          │
│ T05        ┆ 2300.0     ┆ 435752     ┆ 15687072   ┆ 302.892443 ┆ 493.76336 ┆ 0.131692 ┆ 0.21468  │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ T17        ┆ 2300.0     ┆ 433358     ┆ 15600888   ┆ 269.304601 ┆ 454.38989 ┆ 0.117089 ┆ 0.197561 │
│            ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ T18        ┆ 2300.0     ┆ 434521     ┆ 15642756   ┆ 268.205111 ┆ 454.69553 ┆ 0.116611 ┆ 0.197694 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ T19        ┆ 2300.0     ┆ 435327     ┆ 15671772   ┆ 313.134835 ┆ 506.19696 ┆ 0.136146 ┆ 0.220086 │
│            ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ T20        ┆ 2300.0     ┆ 428020     ┆ 15408720   ┆ 306.612361 ┆ 499.67435 ┆ 0.13331  ┆ 0.21725  │
│ T21        ┆ 2300.0     ┆ 435751     ┆ 15687036   ┆ 308.630364 ┆ 508.78451 ┆ 0.134187 ┆ 0.221211 │
│            ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [5]:
# sdwpf_full
sdwpf_full_result = run_persistence_experiment(
    "sdwpf_full",
    cache_root=CACHE_ROOT,
    quality_profile="official_v1",
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(sdwpf_full_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ sdwpf_full ┆ official_v ┆ 1500.0     ┆ 134      ┆ … ┆ 0.189  ┆ 0.261   ┆ 2020-01-01 ┆ 2022-01-01 │
│            ┆ 1          ┆            ┆          ┆   ┆        ┆         ┆ 00:10:00   ┆ 00:10:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 396722        ┆ 81.709  ┆ 123.837 ┆ 0.054  ┆ 0.083   │
│ 2            ┆ 20              ┆ 396722        ┆ 115.474 ┆ 171.758 ┆ 0.077  ┆ 0.115   │
│ 3            ┆ 30              ┆ 396722        ┆ 138.711 ┆ 202.508 ┆ 0.092  ┆ 0.135   │
│ 4            ┆ 40              ┆ 396722        ┆ 157.126 ┆ 226.223 ┆ 0.105  ┆ 0.151   │
│ 5            ┆ 50              ┆ 396722        ┆ 173.216 ┆ 246.262 ┆ 0.115  ┆ 0.164   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 396722        ┆ 376.533 ┆ 488.752 ┆ 0.251  ┆ 0.326   │
│ 33           ┆ 330             ┆ 396722        ┆ 381.118 ┆ 494.128 ┆ 0.254  ┆ 0.329   │
│ 34           ┆ 340             ┆ 396722        ┆ 385.708 ┆ 499.314 ┆ 0.257  ┆ 0.333   │
│ 35           ┆ 350             ┆ 396722        ┆ 390.694 ┆ 504.754 ┆ 0.26   ┆ 0.337   │
│ 36           ┆ 360             ┆ 396722        ┆ 396.457 ┆ 511.268 ┆ 0.264  ┆ 0.341   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (134, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1          ┆ 1500.0        ┆ 2913          ┆ 104868       ┆ 257.974 ┆ 365.304 ┆ 0.172  ┆ 0.244   │
│ 2          ┆ 1500.0        ┆ 2715          ┆ 97740        ┆ 272.466 ┆ 372.234 ┆ 0.182  ┆ 0.248   │
│ 3          ┆ 1500.0        ┆ 3335          ┆ 120060       ┆ 292.581 ┆ 397.891 ┆ 0.195  ┆ 0.265   │
│ 4          ┆ 1500.0        ┆ 2249          ┆ 80964        ┆ 302.77  ┆ 408.571 ┆ 0.202  ┆ 0.272   │
│ 5          ┆ 1500.0        ┆ 3188          ┆ 114768       ┆ 279.501 ┆ 383.128 ┆ 0.186  ┆ 0.255   │
│ …          ┆ …             ┆ …             ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ 130        ┆ 1500.0        ┆ 3099          ┆ 111564       ┆ 267.248 ┆ 369.84  ┆ 0.178  ┆ 0.247   │
│ 131        ┆ 1500.0        ┆ 2991          ┆ 107676       ┆ 301.601 ┆ 413.191 ┆ 0.201  ┆ 0.275   │
│ 132        ┆ 1500.0        ┆ 3056          ┆ 110016       ┆ 287.524 ┆ 399.185 ┆ 0.192  ┆ 0.266   │
│ 133        ┆ 1500.0        ┆ 2568          ┆ 92448        ┆ 275.014 ┆ 373.684 ┆ 0.183  ┆ 0.249   │
│ 134        ┆ 1500.0        ┆ 2637          ┆ 94932        ┆ 268.605 ┆ 365.972 ┆ 0.179  ┆ 0.244   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_pow ┆ turbines ┆ … ┆ mae_pu   ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ er_kw     ┆ ---      ┆   ┆ ---      ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---       ┆ i64      ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64       ┆          ┆   ┆          ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ sdwpf_full ┆ official_v ┆ 1500.0    ┆ 134      ┆ … ┆ 0.189473 ┆ 0.260709 ┆ 2020-01-0 ┆ 2022-01-0 │
│            ┆ 1          ┆           ┆          ┆   ┆          ┆          ┆ 1         ┆ 1         │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ 00:10:00  ┆ 00:10:00  │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 396722        ┆ 81.708591  ┆ 123.836536 ┆ 0.054472 ┆ 0.082558 │
│ 2            ┆ 20              ┆ 396722        ┆ 115.474378 ┆ 171.758226 ┆ 0.076983 ┆ 0.114505 │
│ 3            ┆ 30              ┆ 396722        ┆ 138.711376 ┆ 202.507984 ┆ 0.092474 ┆ 0.135005 │
│ 4            ┆ 40              ┆ 396722        ┆ 157.125672 ┆ 226.223408 ┆ 0.10475  ┆ 0.150816 │
│ 5            ┆ 50              ┆ 396722        ┆ 173.216126 ┆ 246.262435 ┆ 0.115477 ┆ 0.164175 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 396722        ┆ 376.533394 ┆ 488.751881 ┆ 0.251022 ┆ 0.325835 │
│ 33           ┆ 330             ┆ 396722        ┆ 381.118227 ┆ 494.128062 ┆ 0.254079 ┆ 0.329419 │
│ 34           ┆ 340             ┆ 396722        ┆ 385.707612 ┆ 499.314272 ┆ 0.257138 ┆ 0.332876 │
│ 35           ┆ 350             ┆ 396722        ┆ 390.694198 ┆ 504.753598 ┆ 0.260463 ┆ 0.336502 │
│ 36           ┆ 360             ┆ 396722        ┆ 396.457152 ┆ 511.267871 ┆ 0.264305 ┆ 0.340845 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (134, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ 1          ┆ 1500.0     ┆ 2913       ┆ 104868     ┆ 257.973728 ┆ 365.30353 ┆ 0.171982 ┆ 0.243536 │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
│ 2          ┆ 1500.0     ┆ 2715       ┆ 97740      ┆ 272.466478 ┆ 372.23405 ┆ 0.181644 ┆ 0.248156 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ 3          ┆ 1500.0     ┆ 3335       ┆ 120060     ┆ 292.580635 ┆ 397.89129 ┆ 0.195054 ┆ 0.265261 │
│            ┆            ┆            ┆            ┆            ┆ 9         ┆          ┆          │
│ 4          ┆ 1500.0     ┆ 2249       ┆ 80964      ┆ 302.770481 ┆ 408.57054 ┆ 0.201847 ┆ 0.27238  │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
│ 5          ┆ 1500.0     ┆ 3188       ┆ 114768     ┆ 279.50061  ┆ 383.12827 ┆ 0.186334 ┆ 0.255419 │
│            ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ 130        ┆ 1500.0     ┆ 3099       ┆ 111564     ┆ 267.248106 ┆ 369.83998 ┆ 0.178165 ┆ 0.24656  │
│            ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ 131        ┆ 1500.0     ┆ 2991       ┆ 107676     ┆ 301.601037 ┆ 413.19136 ┆ 0.201067 ┆ 0.275461 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ 132        ┆ 1500.0     ┆ 3056       ┆ 110016     ┆ 287.524093 ┆ 399.18455 ┆ 0.191683 ┆ 0.266123 │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
│ 133        ┆ 1500.0     ┆ 2568       ┆ 92448      ┆ 275.013637 ┆ 373.68362 ┆ 0.183342 ┆ 0.249122 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ 134        ┆ 1500.0     ┆ 2637       ┆ 94932      ┆ 268.605221 ┆ 365.97198 ┆ 0.17907  ┆ 0.243981 │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)