In [1]:
from pathlib import Path
import sys

import polars as pl
from IPython.display import display


def _find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").exists():
            return candidate
    raise FileNotFoundError("Unable to locate the repository root from the notebook working directory.")


REPO_ROOT = _find_repo_root(Path.cwd())
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

CACHE_ROOT = REPO_ROOT / "cache"

from wind_datasets.models import TaskSpec
from wind_datasets.persistence import PersistenceExperimentResult, run_persistence_experiment

# Persistence baselines operate on turbine-level series even though the default task is farm-level.
PERSISTENCE_TASK = TaskSpec.next_6h_from_24h(granularity="turbine")


def _round_metrics(frame: pl.DataFrame) -> pl.DataFrame:
    rounded_columns = [column for column in ["mae_kw", "rmse_kw", "mae_pu", "rmse_pu"] if column in frame.columns]
    if not rounded_columns:
        return frame
    return frame.with_columns([pl.col(column).round(3) for column in rounded_columns])


def display_persistence_result(result: PersistenceExperimentResult) -> PersistenceExperimentResult:
    summary = _round_metrics(result.summary).with_columns(
        [
            pl.col("start_timestamp").dt.strftime("%Y-%m-%d %H:%M:%S"),
            pl.col("end_timestamp").dt.strftime("%Y-%m-%d %H:%M:%S"),
        ]
    )
    per_horizon = _round_metrics(result.per_horizon.sort("horizon_step"))
    per_turbine = _round_metrics(result.per_turbine)
    display(summary)
    display(per_horizon)
    display(per_turbine)
    return result

In [2]:
# kelmarsh
kelmarsh_result = run_persistence_experiment(
    "kelmarsh",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(kelmarsh_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ kelmarsh   ┆ default    ┆ 2050.0     ┆ 6        ┆ … ┆ 0.121  ┆ 0.188   ┆ 2016-01-03 ┆ 2024-12-31 │
│            ┆            ┆            ┆          ┆   ┆        ┆         ┆ 00:00:00   ┆ 23:50:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 2641667       ┆ 93.0    ┆ 153.675 ┆ 0.045  ┆ 0.075   │
│ 2            ┆ 20              ┆ 2641667       ┆ 124.905 ┆ 203.042 ┆ 0.061  ┆ 0.099   │
│ 3            ┆ 30              ┆ 2641667       ┆ 143.617 ┆ 230.915 ┆ 0.07   ┆ 0.113   │
│ 4            ┆ 40              ┆ 2641667       ┆ 157.468 ┆ 251.115 ┆ 0.077  ┆ 0.122   │
│ 5            ┆ 50              ┆ 2641667       ┆ 168.787 ┆ 267.445 ┆ 0.082  ┆ 0.13    │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 2641667       ┆ 316.293 ┆ 468.623 ┆ 0.154  ┆ 0.229   │
│ 33           ┆ 330             ┆ 2641667       ┆ 320.027 ┆ 473.421 ┆ 0.156  ┆ 0.231   │
│ 34           ┆ 340             ┆ 2641667       ┆ 323.618 ┆ 478.043 ┆ 0.158  ┆ 0.233   │
│ 35           ┆ 350             ┆ 2641667       ┆ 327.185 ┆ 482.577 ┆ 0.16   ┆ 0.235   │
│ 36           ┆ 360             ┆ 2641667       ┆ 330.606 ┆ 486.98  ┆ 0.161  ┆ 0.238   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (6, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ Kelmarsh 1 ┆ 2050.0        ┆ 442592        ┆ 15933312     ┆ 250.655 ┆ 387.038 ┆ 0.122  ┆ 0.189   │
│ Kelmarsh 2 ┆ 2050.0        ┆ 444783        ┆ 16012188     ┆ 258.902 ┆ 394.363 ┆ 0.126  ┆ 0.192   │
│ Kelmarsh 3 ┆ 2050.0        ┆ 441356        ┆ 15888816     ┆ 256.359 ┆ 396.447 ┆ 0.125  ┆ 0.193   │
│ Kelmarsh 4 ┆ 2050.0        ┆ 438563        ┆ 15788268     ┆ 244.331 ┆ 379.266 ┆ 0.119  ┆ 0.185   │
│ Kelmarsh 5 ┆ 2050.0        ┆ 437738        ┆ 15758568     ┆ 249.71  ┆ 390.871 ┆ 0.122  ┆ 0.191   │
│ Kelmarsh 6 ┆ 2050.0        ┆ 436635        ┆ 15718860     ┆ 224.059 ┆ 358.857 ┆ 0.109  ┆ 0.175   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu  ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---     ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64     ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64        ┆          ┆   ┆         ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ kelmarsh   ┆ default    ┆ 2050.0     ┆ 6        ┆ … ┆ 0.12068 ┆ 0.187678 ┆ 2016-01-0 ┆ 2024-12-3 │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ 3         ┆ 1         │
│            ┆            ┆            ┆          ┆   ┆         ┆          ┆ 00:00:00  ┆ 23:50:00  │
└────────────┴────────────┴────────────┴──────────┴───┴─────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 2641667       ┆ 92.999595  ┆ 153.6753   ┆ 0.045366 ┆ 0.074964 │
│ 2            ┆ 20              ┆ 2641667       ┆ 124.904623 ┆ 203.042098 ┆ 0.060929 ┆ 0.099045 │
│ 3            ┆ 30              ┆ 2641667       ┆ 143.616838 ┆ 230.91462  ┆ 0.070057 ┆ 0.112641 │
│ 4            ┆ 40              ┆ 2641667       ┆ 157.467857 ┆ 251.115016 ┆ 0.076814 ┆ 0.122495 │
│ 5            ┆ 50              ┆ 2641667       ┆ 168.787367 ┆ 267.444623 ┆ 0.082335 ┆ 0.130461 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 2641667       ┆ 316.292848 ┆ 468.623117 ┆ 0.154289 ┆ 0.228597 │
│ 33           ┆ 330             ┆ 2641667       ┆ 320.026566 ┆ 473.421257 ┆ 0.156111 ┆ 0.230937 │
│ 34           ┆ 340             ┆ 2641667       ┆ 323.617862 ┆ 478.042615 ┆ 0.157862 ┆ 0.233192 │
│ 35           ┆ 350             ┆ 2641667       ┆ 327.185475 ┆ 482.576782 ┆ 0.159603 ┆ 0.235403 │
│ 36           ┆ 360             ┆ 2641667       ┆ 330.606042 ┆ 486.979789 ┆ 0.161271 ┆ 0.237551 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (6, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ Kelmarsh 1 ┆ 2050.0     ┆ 442592     ┆ 15933312   ┆ 250.655033 ┆ 387.03829 ┆ 0.122271 ┆ 0.188799 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Kelmarsh 2 ┆ 2050.0     ┆ 444783     ┆ 16012188   ┆ 258.902195 ┆ 394.36294 ┆ 0.126294 ┆ 0.192372 │
│ Kelmarsh 3 ┆ 2050.0     ┆ 441356     ┆ 15888816   ┆ 256.35862  ┆ 396.44714 ┆ 0.125053 ┆ 0.193389 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ Kelmarsh 4 ┆ 2050.0     ┆ 438563     ┆ 15788268   ┆ 244.330555 ┆ 379.26575 ┆ 0.119186 ┆ 0.185008 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Kelmarsh 5 ┆ 2050.0     ┆ 437738     ┆ 15758568   ┆ 249.710233 ┆ 390.87115 ┆ 0.12181  ┆ 0.190669 │
│ Kelmarsh 6 ┆ 2050.0     ┆ 436635     ┆ 15718860   ┆ 224.059456 ┆ 358.85733 ┆ 0.109297 ┆ 0.175052 │
│            ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [3]:
# penmanshiel
penmanshiel_result = run_persistence_experiment(
    "penmanshiel",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(penmanshiel_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ penmanshie ┆ default    ┆ 2050.0     ┆ 14       ┆ … ┆ 0.137  ┆ 0.221   ┆ 2016-06-02 ┆ 2024-12-31 │
│ l          ┆            ┆            ┆          ┆   ┆        ┆         ┆ 17:40:00   ┆ 23:50:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 5405463       ┆ 93.841  ┆ 163.922 ┆ 0.046  ┆ 0.08    │
│ 2            ┆ 20              ┆ 5405463       ┆ 129.778 ┆ 224.378 ┆ 0.063  ┆ 0.109   │
│ 3            ┆ 30              ┆ 5405463       ┆ 151.008 ┆ 257.312 ┆ 0.074  ┆ 0.126   │
│ 4            ┆ 40              ┆ 5405463       ┆ 166.915 ┆ 281.487 ┆ 0.081  ┆ 0.137   │
│ 5            ┆ 50              ┆ 5405463       ┆ 180.345 ┆ 301.687 ┆ 0.088  ┆ 0.147   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 5405463       ┆ 368.081 ┆ 558.016 ┆ 0.18   ┆ 0.272   │
│ 33           ┆ 330             ┆ 5405463       ┆ 372.857 ┆ 564.051 ┆ 0.182  ┆ 0.275   │
│ 34           ┆ 340             ┆ 5405463       ┆ 377.536 ┆ 570.0   ┆ 0.184  ┆ 0.278   │
│ 35           ┆ 350             ┆ 5405463       ┆ 382.205 ┆ 575.893 ┆ 0.186  ┆ 0.281   │
│ 36           ┆ 360             ┆ 5405463       ┆ 386.819 ┆ 581.639 ┆ 0.189  ┆ 0.284   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (14, 8)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id   ┆ rated_power_ ┆ eligible_win ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ kw           ┆ dows         ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str          ┆ ---          ┆ ---          ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│              ┆ f64          ┆ i64          ┆ i64          ┆         ┆         ┆        ┆         │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ Penmanshiel  ┆ 2050.0       ┆ 373157       ┆ 13433652     ┆ 284.58  ┆ 455.726 ┆ 0.139  ┆ 0.222   │
│ 01           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 372824       ┆ 13421664     ┆ 282.995 ┆ 455.297 ┆ 0.138  ┆ 0.222   │
│ 02           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 370240       ┆ 13328640     ┆ 280.819 ┆ 452.658 ┆ 0.137  ┆ 0.221   │
│ 04           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 372353       ┆ 13404708     ┆ 278.401 ┆ 450.076 ┆ 0.136  ┆ 0.22    │
│ 05           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 371045       ┆ 13357620     ┆ 275.941 ┆ 451.497 ┆ 0.135  ┆ 0.22    │
│ 06           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ …            ┆ …            ┆ …            ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ Penmanshiel  ┆ 2050.0       ┆ 412236       ┆ 14840496     ┆ 277.775 ┆ 445.994 ┆ 0.135  ┆ 0.218   │
│ 11           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 417785       ┆ 15040260     ┆ 294.18  ┆ 469.169 ┆ 0.144  ┆ 0.229   │
│ 12           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 418476       ┆ 15065136     ┆ 297.512 ┆ 474.182 ┆ 0.145  ┆ 0.231   │
│ 13           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 416576       ┆ 14996736     ┆ 292.336 ┆ 468.391 ┆ 0.143  ┆ 0.228   │
│ 14           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
│ Penmanshiel  ┆ 2050.0       ┆ 416763       ┆ 15003468     ┆ 287.698 ┆ 460.778 ┆ 0.14   ┆ 0.225   │
│ 15           ┆              ┆              ┆              ┆         ┆         ┆        ┆         │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_pow ┆ turbines ┆ … ┆ mae_pu   ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ er_kw     ┆ ---      ┆   ┆ ---      ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---       ┆ i64      ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64       ┆          ┆   ┆          ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ penmanshie ┆ default    ┆ 2050.0    ┆ 14       ┆ … ┆ 0.136658 ┆ 0.220651 ┆ 2016-06-0 ┆ 2024-12-3 │
│ l          ┆            ┆           ┆          ┆   ┆          ┆          ┆ 2         ┆ 1         │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ 17:40:00  ┆ 23:50:00  │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 5405463       ┆ 93.841083  ┆ 163.922004 ┆ 0.045776 ┆ 0.079962 │
│ 2            ┆ 20              ┆ 5405463       ┆ 129.778479 ┆ 224.378122 ┆ 0.063307 ┆ 0.109453 │
│ 3            ┆ 30              ┆ 5405463       ┆ 151.008225 ┆ 257.311688 ┆ 0.073663 ┆ 0.125518 │
│ 4            ┆ 40              ┆ 5405463       ┆ 166.915208 ┆ 281.486787 ┆ 0.081422 ┆ 0.137311 │
│ 5            ┆ 50              ┆ 5405463       ┆ 180.344707 ┆ 301.68679  ┆ 0.087973 ┆ 0.147164 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 5405463       ┆ 368.081414 ┆ 558.016302 ┆ 0.179552 ┆ 0.272203 │
│ 33           ┆ 330             ┆ 5405463       ┆ 372.857095 ┆ 564.050917 ┆ 0.181882 ┆ 0.275147 │
│ 34           ┆ 340             ┆ 5405463       ┆ 377.536423 ┆ 569.999683 ┆ 0.184164 ┆ 0.278049 │
│ 35           ┆ 350             ┆ 5405463       ┆ 382.20489  ┆ 575.893042 ┆ 0.186441 ┆ 0.280923 │
│ 36           ┆ 360             ┆ 5405463       ┆ 386.818896 ┆ 581.63851  ┆ 0.188692 ┆ 0.283726 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (14, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ Penmanshie ┆ 2050.0     ┆ 373157     ┆ 13433652   ┆ 284.579514 ┆ 455.72555 ┆ 0.138819 ┆ 0.222305 │
│ l 01       ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 372824     ┆ 13421664   ┆ 282.994838 ┆ 455.29748 ┆ 0.138046 ┆ 0.222096 │
│ l 02       ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 370240     ┆ 13328640   ┆ 280.818743 ┆ 452.65772 ┆ 0.136985 ┆ 0.220809 │
│ l 04       ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 372353     ┆ 13404708   ┆ 278.400531 ┆ 450.07611 ┆ 0.135805 ┆ 0.219549 │
│ l 05       ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 371045     ┆ 13357620   ┆ 275.940738 ┆ 451.49654 ┆ 0.134605 ┆ 0.220242 │
│ l 06       ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ Penmanshie ┆ 2050.0     ┆ 412236     ┆ 14840496   ┆ 277.774536 ┆ 445.99394 ┆ 0.1355   ┆ 0.217558 │
│ l 11       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 417785     ┆ 15040260   ┆ 294.180476 ┆ 469.1694  ┆ 0.143503 ┆ 0.228863 │
│ l 12       ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 418476     ┆ 15065136   ┆ 297.512236 ┆ 474.18245 ┆ 0.145128 ┆ 0.231309 │
│ l 13       ┆            ┆            ┆            ┆            ┆ 5         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 416576     ┆ 14996736   ┆ 292.335604 ┆ 468.39080 ┆ 0.142603 ┆ 0.228483 │
│ l 14       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ Penmanshie ┆ 2050.0     ┆ 416763     ┆ 15003468   ┆ 287.698274 ┆ 460.77819 ┆ 0.140341 ┆ 0.22477  │
│ l 15       ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [4]:
# hill_of_towie
hill_of_towie_result = run_persistence_experiment(
    "hill_of_towie",
    cache_root=CACHE_ROOT,
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(hill_of_towie_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ hill_of_to ┆ default    ┆ 2300.0     ┆ 21       ┆ … ┆ 0.13   ┆ 0.213   ┆ 2016-01-01 ┆ 2024-09-01 │
│ wie        ┆            ┆            ┆          ┆   ┆        ┆         ┆ 00:00:00   ┆ 00:00:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 9115020       ┆ 109.176 ┆ 192.066 ┆ 0.047  ┆ 0.084   │
│ 2            ┆ 20              ┆ 9115020       ┆ 151.708 ┆ 264.36  ┆ 0.066  ┆ 0.115   │
│ 3            ┆ 30              ┆ 9115020       ┆ 176.017 ┆ 304.142 ┆ 0.077  ┆ 0.132   │
│ 4            ┆ 40              ┆ 9115020       ┆ 193.276 ┆ 331.56  ┆ 0.084  ┆ 0.144   │
│ 5            ┆ 50              ┆ 9115020       ┆ 207.027 ┆ 352.745 ┆ 0.09   ┆ 0.153   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 9115020       ┆ 378.302 ┆ 589.561 ┆ 0.164  ┆ 0.256   │
│ 33           ┆ 330             ┆ 9115020       ┆ 382.626 ┆ 595.128 ┆ 0.166  ┆ 0.259   │
│ 34           ┆ 340             ┆ 9115020       ┆ 386.862 ┆ 600.604 ┆ 0.168  ┆ 0.261   │
│ 35           ┆ 350             ┆ 9115020       ┆ 391.031 ┆ 605.858 ┆ 0.17   ┆ 0.263   │
│ 36           ┆ 360             ┆ 9115020       ┆ 395.083 ┆ 610.959 ┆ 0.172  ┆ 0.266   │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (21, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ T01        ┆ 2300.0        ┆ 435469        ┆ 15676884     ┆ 306.241 ┆ 498.027 ┆ 0.133  ┆ 0.217   │
│ T02        ┆ 2300.0        ┆ 435035        ┆ 15661260     ┆ 293.347 ┆ 484.486 ┆ 0.128  ┆ 0.211   │
│ T03        ┆ 2300.0        ┆ 435446        ┆ 15676056     ┆ 311.699 ┆ 503.851 ┆ 0.136  ┆ 0.219   │
│ T04        ┆ 2300.0        ┆ 434831        ┆ 15653916     ┆ 315.918 ┆ 510.4   ┆ 0.137  ┆ 0.222   │
│ T05        ┆ 2300.0        ┆ 435032        ┆ 15661152     ┆ 302.802 ┆ 493.616 ┆ 0.132  ┆ 0.215   │
│ …          ┆ …             ┆ …             ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ T17        ┆ 2300.0        ┆ 432638        ┆ 15574968     ┆ 269.246 ┆ 454.235 ┆ 0.117  ┆ 0.197   │
│ T18        ┆ 2300.0        ┆ 433801        ┆ 15616836     ┆ 268.135 ┆ 454.499 ┆ 0.117  ┆ 0.198   │
│ T19        ┆ 2300.0        ┆ 434607        ┆ 15645852     ┆ 313.027 ┆ 505.986 ┆ 0.136  ┆ 0.22    │
│ T20        ┆ 2300.0        ┆ 427300        ┆ 15382800     ┆ 306.521 ┆ 499.484 ┆ 0.133  ┆ 0.217   │
│ T21        ┆ 2300.0        ┆ 435031        ┆ 15661116     ┆ 308.765 ┆ 508.962 ┆ 0.134  ┆ 0.221   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_pow ┆ turbines ┆ … ┆ mae_pu   ┆ rmse_pu  ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ er_kw     ┆ ---      ┆   ┆ ---      ┆ ---      ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---       ┆ i64      ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64       ┆          ┆   ┆          ┆          ┆ datetime[ ┆ datetime[ │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ hill_of_to ┆ default    ┆ 2300.0    ┆ 21       ┆ … ┆ 0.129563 ┆ 0.213262 ┆ 2016-01-0 ┆ 2024-09-0 │
│ wie        ┆            ┆           ┆          ┆   ┆          ┆          ┆ 1         ┆ 1         │
│            ┆            ┆           ┆          ┆   ┆          ┆          ┆ 00:00:00  ┆ 00:00:00  │
└────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 9115020       ┆ 109.176216 ┆ 192.065922 ┆ 0.047468 ┆ 0.083507 │
│ 2            ┆ 20              ┆ 9115020       ┆ 151.707744 ┆ 264.360214 ┆ 0.06596  ┆ 0.114939 │
│ 3            ┆ 30              ┆ 9115020       ┆ 176.017237 ┆ 304.142361 ┆ 0.076529 ┆ 0.132236 │
│ 4            ┆ 40              ┆ 9115020       ┆ 193.275662 ┆ 331.560359 ┆ 0.084033 ┆ 0.144157 │
│ 5            ┆ 50              ┆ 9115020       ┆ 207.026821 ┆ 352.745045 ┆ 0.090012 ┆ 0.153367 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 9115020       ┆ 378.301866 ┆ 589.560937 ┆ 0.164479 ┆ 0.256331 │
│ 33           ┆ 330             ┆ 9115020       ┆ 382.625851 ┆ 595.128382 ┆ 0.166359 ┆ 0.258751 │
│ 34           ┆ 340             ┆ 9115020       ┆ 386.861873 ┆ 600.604458 ┆ 0.168201 ┆ 0.261132 │
│ 35           ┆ 350             ┆ 9115020       ┆ 391.031244 ┆ 605.857774 ┆ 0.170014 ┆ 0.263416 │
│ 36           ┆ 360             ┆ 9115020       ┆ 395.082969 ┆ 610.958806 ┆ 0.171775 ┆ 0.265634 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (21, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ T01        ┆ 2300.0     ┆ 435469     ┆ 15676884   ┆ 306.241473 ┆ 498.02677 ┆ 0.133148 ┆ 0.216533 │
│            ┆            ┆            ┆            ┆            ┆ 5         ┆          ┆          │
│ T02        ┆ 2300.0     ┆ 435035     ┆ 15661260   ┆ 293.346568 ┆ 484.48635 ┆ 0.127542 ┆ 0.210646 │
│            ┆            ┆            ┆            ┆            ┆ 7         ┆          ┆          │
│ T03        ┆ 2300.0     ┆ 435446     ┆ 15676056   ┆ 311.699455 ┆ 503.85070 ┆ 0.135522 ┆ 0.219066 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ T04        ┆ 2300.0     ┆ 434831     ┆ 15653916   ┆ 315.918295 ┆ 510.39969 ┆ 0.137356 ┆ 0.221913 │
│            ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
│ T05        ┆ 2300.0     ┆ 435032     ┆ 15661152   ┆ 302.802081 ┆ 493.61583 ┆ 0.131653 ┆ 0.214616 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ T17        ┆ 2300.0     ┆ 432638     ┆ 15574968   ┆ 269.24558  ┆ 454.23457 ┆ 0.117063 ┆ 0.197493 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ T18        ┆ 2300.0     ┆ 433801     ┆ 15616836   ┆ 268.134821 ┆ 454.49898 ┆ 0.11658  ┆ 0.197608 │
│            ┆            ┆            ┆            ┆            ┆ 5         ┆          ┆          │
│ T19        ┆ 2300.0     ┆ 434607     ┆ 15645852   ┆ 313.026509 ┆ 505.98626 ┆ 0.136098 ┆ 0.219994 │
│ T20        ┆ 2300.0     ┆ 427300     ┆ 15382800   ┆ 306.520873 ┆ 499.48439 ┆ 0.13327  ┆ 0.217167 │
│            ┆            ┆            ┆            ┆            ┆ 2         ┆          ┆          │
│ T21        ┆ 2300.0     ┆ 435031     ┆ 15661116   ┆ 308.764846 ┆ 508.96159 ┆ 0.134246 ┆ 0.221288 │
│            ┆            ┆            ┆            ┆            ┆ 6         ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)

In [5]:
# sdwpf_kddcup
sdwpf_kddcup_result = run_persistence_experiment(
    "sdwpf_kddcup",
    cache_root=CACHE_ROOT,
    quality_profile="default",
    task_spec=PERSISTENCE_TASK,
)
display_persistence_result(sdwpf_kddcup_result)

shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬────────┬─────────┬────────────┬────────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu ┆ rmse_pu ┆ start_time ┆ end_timest │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---    ┆ ---     ┆ stamp      ┆ amp        │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64    ┆ f64     ┆ ---        ┆ ---        │
│            ┆ str        ┆ f64        ┆          ┆   ┆        ┆         ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪══════════╪═══╪════════╪═════════╪════════════╪════════════╡
│ sdwpf_kddc ┆ default    ┆ 1500.0     ┆ 134      ┆ … ┆ 0.163  ┆ 0.235   ┆ 2020-05-01 ┆ 2020-12-31 │
│ up         ┆            ┆            ┆          ┆   ┆        ┆         ┆ 00:00:00   ┆ 23:50:00   │
└────────────┴────────────┴────────────┴──────────┴───┴────────┴─────────┴────────────┴────────────┘

shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬─────────┬─────────┬────────┬─────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---          ┆ ---             ┆ ---           ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ i64          ┆ i64             ┆ i64           ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
╞══════════════╪═════════════════╪═══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1            ┆ 10              ┆ 269772        ┆ 75.22   ┆ 120.455 ┆ 0.05   ┆ 0.08    │
│ 2            ┆ 20              ┆ 269772        ┆ 104.769 ┆ 163.493 ┆ 0.07   ┆ 0.109   │
│ 3            ┆ 30              ┆ 269772        ┆ 125.527 ┆ 191.861 ┆ 0.084  ┆ 0.128   │
│ 4            ┆ 40              ┆ 269772        ┆ 142.639 ┆ 214.276 ┆ 0.095  ┆ 0.143   │
│ 5            ┆ 50              ┆ 269772        ┆ 157.267 ┆ 233.107 ┆ 0.105  ┆ 0.155   │
│ …            ┆ …               ┆ …             ┆ …       ┆ …       ┆ …      ┆ …       │
│ 32           ┆ 320             ┆ 269772        ┆ 320.654 ┆ 438.862 ┆ 0.214  ┆ 0.293   │
│ 33           ┆ 330             ┆ 269772        ┆ 325.213 ┆ 444.783 ┆ 0.217  ┆ 0.297   │
│ 34           ┆ 340             ┆ 269772        ┆ 329.993 ┆ 450.974 ┆ 0.22   ┆ 0.301   │
│ 35           ┆ 350             ┆ 269772        ┆ 335.413 ┆ 457.644 ┆ 0.224  ┆ 0.305   │
│ 36           ┆ 360             ┆ 269772        ┆ 341.785 ┆ 465.727 ┆ 0.228  ┆ 0.31    │
└──────────────┴─────────────────┴───────────────┴─────────┴─────────┴────────┴─────────┘

shape: (134, 8)
┌────────────┬───────────────┬───────────────┬──────────────┬─────────┬─────────┬────────┬─────────┐
│ turbine_id ┆ rated_power_k ┆ eligible_wind ┆ prediction_c ┆ mae_kw  ┆ rmse_kw ┆ mae_pu ┆ rmse_pu │
│ ---        ┆ w             ┆ ows           ┆ ount         ┆ ---     ┆ ---     ┆ ---    ┆ ---     │
│ str        ┆ ---           ┆ ---           ┆ ---          ┆ f64     ┆ f64     ┆ f64    ┆ f64     │
│            ┆ f64           ┆ i64           ┆ i64          ┆         ┆         ┆        ┆         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪═════════╪═════════╪════════╪═════════╡
│ 1          ┆ 1500.0        ┆ 3655          ┆ 131580       ┆ 232.359 ┆ 365.875 ┆ 0.155  ┆ 0.244   │
│ 2          ┆ 1500.0        ┆ 2012          ┆ 72432        ┆ 264.757 ┆ 384.474 ┆ 0.177  ┆ 0.256   │
│ 3          ┆ 1500.0        ┆ 2446          ┆ 88056        ┆ 255.181 ┆ 365.283 ┆ 0.17   ┆ 0.244   │
│ 4          ┆ 1500.0        ┆ 1978          ┆ 71208        ┆ 275.067 ┆ 393.07  ┆ 0.183  ┆ 0.262   │
│ 5          ┆ 1500.0        ┆ 2466          ┆ 88776        ┆ 257.909 ┆ 379.324 ┆ 0.172  ┆ 0.253   │
│ …          ┆ …             ┆ …             ┆ …            ┆ …       ┆ …       ┆ …      ┆ …       │
│ 130        ┆ 1500.0        ┆ 2248          ┆ 80928        ┆ 266.212 ┆ 381.025 ┆ 0.177  ┆ 0.254   │
│ 131        ┆ 1500.0        ┆ 2623          ┆ 94428        ┆ 244.276 ┆ 358.498 ┆ 0.163  ┆ 0.239   │
│ 132        ┆ 1500.0        ┆ 1779          ┆ 64044        ┆ 212.992 ┆ 299.03  ┆ 0.142  ┆ 0.199   │
│ 133        ┆ 1500.0        ┆ 1666          ┆ 59976        ┆ 223.749 ┆ 315.63  ┆ 0.149  ┆ 0.21    │
│ 134        ┆ 1500.0        ┆ 1795          ┆ 64620        ┆ 244.542 ┆ 341.765 ┆ 0.163  ┆ 0.228   │
└────────────┴───────────────┴───────────────┴──────────────┴─────────┴─────────┴────────┴─────────┘

PersistenceExperimentResult(summary=shape: (1, 12)
┌────────────┬────────────┬────────────┬──────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ dataset_id ┆ quality_pr ┆ rated_powe ┆ turbines ┆ … ┆ mae_pu   ┆ rmse_pu ┆ start_tim ┆ end_times │
│ ---        ┆ ofile      ┆ r_kw       ┆ ---      ┆   ┆ ---      ┆ ---     ┆ estamp    ┆ tamp      │
│ str        ┆ ---        ┆ ---        ┆ i64      ┆   ┆ f64      ┆ f64     ┆ ---       ┆ ---       │
│            ┆ str        ┆ f64        ┆          ┆   ┆          ┆         ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆          ┆   ┆          ┆         ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪══════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ sdwpf_kddc ┆ default    ┆ 1500.0     ┆ 134      ┆ … ┆ 0.162605 ┆ 0.23494 ┆ 2020-05-0 ┆ 2020-12-3 │
│ up         ┆            ┆            ┆          ┆   ┆          ┆         ┆ 1         ┆ 1         │
│            ┆            ┆            ┆          ┆   ┆          ┆         ┆ 00:00:00  ┆ 23:50:00  │
└────────────┴────────────┴────────────┴──────────┴───┴──────────┴─────────┴───────────┴───────────┘, per_horizon=shape: (36, 7)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬──────────┬──────────┐
│ horizon_step ┆ horizon_minutes ┆ n_predictions ┆ mae_kw     ┆ rmse_kw    ┆ mae_pu   ┆ rmse_pu  │
│ ---          ┆ ---             ┆ ---           ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ i64          ┆ i64             ┆ i64           ┆ f64        ┆ f64        ┆ f64      ┆ f64      │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪══════════╪══════════╡
│ 1            ┆ 10              ┆ 269772        ┆ 75.220223  ┆ 120.454678 ┆ 0.050147 ┆ 0.080303 │
│ 2            ┆ 20              ┆ 269772        ┆ 104.768708 ┆ 163.492545 ┆ 0.069846 ┆ 0.108995 │
│ 3            ┆ 30              ┆ 269772        ┆ 125.527353 ┆ 191.860645 ┆ 0.083685 ┆ 0.127907 │
│ 4            ┆ 40              ┆ 269772        ┆ 142.63887  ┆ 214.276017 ┆ 0.095093 ┆ 0.142851 │
│ 5            ┆ 50              ┆ 269772        ┆ 157.26732  ┆ 233.107233 ┆ 0.104845 ┆ 0.155405 │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …        ┆ …        │
│ 32           ┆ 320             ┆ 269772        ┆ 320.654011 ┆ 438.862031 ┆ 0.213769 ┆ 0.292575 │
│ 33           ┆ 330             ┆ 269772        ┆ 325.212517 ┆ 444.782806 ┆ 0.216808 ┆ 0.296522 │
│ 34           ┆ 340             ┆ 269772        ┆ 329.992771 ┆ 450.973962 ┆ 0.219995 ┆ 0.300649 │
│ 35           ┆ 350             ┆ 269772        ┆ 335.413366 ┆ 457.644152 ┆ 0.223609 ┆ 0.305096 │
│ 36           ┆ 360             ┆ 269772        ┆ 341.785307 ┆ 465.727212 ┆ 0.227857 ┆ 0.310485 │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴──────────┴──────────┘, per_turbine=shape: (134, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ turbine_id ┆ rated_powe ┆ eligible_w ┆ prediction ┆ mae_kw     ┆ rmse_kw   ┆ mae_pu   ┆ rmse_pu  │
│ ---        ┆ r_kw       ┆ indows     ┆ _count     ┆ ---        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ ---        ┆ ---        ┆ f64        ┆ f64       ┆ f64      ┆ f64      │
│            ┆ f64        ┆ i64        ┆ i64        ┆            ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ 1          ┆ 1500.0     ┆ 3655       ┆ 131580     ┆ 232.359459 ┆ 365.87539 ┆ 0.154906 ┆ 0.243917 │
│            ┆            ┆            ┆            ┆            ┆ 9         ┆          ┆          │
│ 2          ┆ 1500.0     ┆ 2012       ┆ 72432      ┆ 264.757465 ┆ 384.47444 ┆ 0.176505 ┆ 0.256316 │
│            ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ 3          ┆ 1500.0     ┆ 2446       ┆ 88056      ┆ 255.180999 ┆ 365.28283 ┆ 0.170121 ┆ 0.243522 │
│ 4          ┆ 1500.0     ┆ 1978       ┆ 71208      ┆ 275.066599 ┆ 393.07003 ┆ 0.183378 ┆ 0.262047 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ 5          ┆ 1500.0     ┆ 2466       ┆ 88776      ┆ 257.909385 ┆ 379.32427 ┆ 0.17194  ┆ 0.252883 │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ 130        ┆ 1500.0     ┆ 2248       ┆ 80928      ┆ 266.211699 ┆ 381.02469 ┆ 0.177474 ┆ 0.254016 │
│            ┆            ┆            ┆            ┆            ┆ 4         ┆          ┆          │
│ 131        ┆ 1500.0     ┆ 2623       ┆ 94428      ┆ 244.276044 ┆ 358.49830 ┆ 0.162851 ┆ 0.238999 │
│            ┆            ┆            ┆            ┆            ┆ 3         ┆          ┆          │
│ 132        ┆ 1500.0     ┆ 1779       ┆ 64044      ┆ 212.992181 ┆ 299.03011 ┆ 0.141995 ┆ 0.199353 │
│            ┆            ┆            ┆            ┆            ┆ 5         ┆          ┆          │
│ 133        ┆ 1500.0     ┆ 1666       ┆ 59976      ┆ 223.749052 ┆ 315.62952 ┆ 0.149166 ┆ 0.21042  │
│            ┆            ┆            ┆            ┆            ┆ 8         ┆          ┆          │
│ 134        ┆ 1500.0     ┆ 1795       ┆ 64620      ┆ 244.542156 ┆ 341.765   ┆ 0.163028 ┆ 0.227843 │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘)